apiVersion: v1
kind: Service
metadata:
  name: nginx-ingress
  namespace: nginx-ingress
  labels:
    app: nginx-ingress
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - port: 8081
      targetPort: 8081
      protocol: TCP
      name: readiness-port
  selector:
      app: nginx-ingress