apiVersion: "cis.f5.com/v1"
kind: TransportServer
metadata:
   name: transport-server
   namespace: nginx-ingress
   labels:
     f5cr: "true"
spec:
  virtualServerAddress: "10.24.1.22"
  virtualServerPort: 8443
  mode: standard
  snat: auto
  pool:
    service: nginx-ingress
    servicePort: 443
    monitor:
      type: tcp
      interval: 10
      timeout: 10
  serviceAddress:
  - icmpEcho: "enable"
    arpEnabled: true
    routeAdvertisement: "all"
    spanningEnabled: false
