apiVersion: "cis.f5.com/v1"
kind: VirtualServer
metadata:
  name: vs-nginx-cafe
  namespace: nginx-ingress
  labels:
    f5cr: "true"
spec:
  # This is an insecure virtual, Please use TLSProfile to secure the virtual
  # check out tls examples to understand more.
  virtualServerAddress: "10.24.1.22"
  virtualServerHTTPSPort: 443
  httpTraffic: redirect
#  waf: /Common/WAF_Policy
#  iRules:
#  - /Common/Portal_SSL_Version
  tlsProfileName: terminate-tls
  host: cafe.example.com
  pools:
  - path: /tea
    service: nginx-ingress
    servicePort: 80
    monitor:
      type: http
      interval: 10
      timeout: 31
      send: 'GET /coffee HTTP/1.1\r\nHost: cafe.example.com\r\nConnection: Close\r\n\r\n'
  - path: /coffee
    service: nginx-ingress
    servicePort: 80
#  - path: /nginx
#    service: nginx-ingress
#    servicePort: 8081
#    monitor:
#      type: http
#      interval: 10
#      timeout: 31
#      send: "GET /nginx-ready\r\n"
  
  
    