apiVersion: cis.f5.com/v1
kind: TLSProfile
metadata:
  name: terminate-tls
  namespace: cafe
  labels:
    f5cr: "true"
spec:
  tls:
    termination: edge
    clientSSL: /Common/clientssl
    reference: bigip
  hosts:
  - cafe.example.com
  - arcadia.dfslab.local